# A sample Gemfile
source "https://rubygems.org"

gem 'rake'
gem 'activesupport'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-activerecord'
gem 'sinatra-flash'

gem 'puma'
gem 'tux'

gem 'twitter'
gem 'geocoder'
gem 'will_paginate', '~> 3.0.6'
gem 'stripe'

group :development, :test do
  gem 'pry'
  gem 'shotgun'
  gem 'sqlite3'

end
  